---
title: "126 final project"
author: "Rebecca Ji, Cindy Liu, Linna He"
date: "2020/6/12"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

link to the data set: https://archive.ics.uci.edu/ml/datasets/student%2Bperformance#


```{r}
#importing data
d1 <- read.table("student-mat.csv",sep=";",header=TRUE)
```

```{r}
#Exploratory plots of the data
d2 <- subset(d1, G3!=0)
par(mfrow = c(1, 2))
plot(d1$G3,  d1$G2) # we found a series of 0-values in G3 of our d1 dataset, and they got removed in new dataset d2
plot(d2$G3,  d2$G2)
lm0 <-lm (G3~G1+G2, data = d1)
plot(lm0) #violate linearity, equal variance rule and normality. 
lm1 <-lm (G3~G1+G2, data = d2)
plot(lm1) #better
```

```{r}
#scattor plot
pairs(~G3 + G2 + G1 + famrel + goout + health + absences + paid)
pairs(~G3 + G2 + famrel + absences + G1 + age ) #code for figure 1: partial scatter plot
#There might be linear relationship between G3 and G1, G2 and G1, and G2 and G3.
```

```{r}
#AV plots for model with potential predictors based on scatter plot
library(alr4)
full.pot<-lm(G3 ~ G2+G1+famrel+health+absences+goout,data=d2)
avPlots(full.pot, id=FALSE)
summary(full.pot)
```


```{r}
attach(d1)
#Variable selection I
#forward selection with aic
mod.0 <- lm(G3~1, data=d2)
mod.full <- lm(G3 ~., data=d2) 
step(mod.0, scope=list(lower=mod.0, upper=mod.full), direction = "forward", trace=0)
#result: G3 ~ G2 + G1 + famrel + goout + health + absences + paid

#forward selection with bic
n <- length(d2$G3)
step(mod.0,scope = list(lower=mod.0,upper=mod.full), direction = "forward", k=log(n),trace=0)
#result: G3 ~ G2 + G1 + famrel

#backward selection with aic
step(mod.full, scope=list(lower=mod.0, upper=mod.full), direction = "backward", trace=0)
#result: G3 ~ paid + famrel + goout + health + absences + G1 + G2

#backward selection with bic
step(mod.full, scope=list(lower=mod.0, upper=mod.full), direction = "backward", k=log(n),trace=0)
#result: G3 ~ famrel + G1 + G2

#stepwise selection
step(mod.0,scope = list(lower=mod.0,upper=mod.full),trace=0)
#result: G3 ~ G2 + G1 + famrel + goout + health + absences + paid

```



```{r}
#Variable selection II
library(leaps)
mod.reg <- regsubsets(cbind(G2, G1, famrel, goout, health, absences, paid),G3, data=d2)
summary.reg<- summary(mod.reg)
summary.reg$which

#by plots
par(mfrow = c(2, 2))
plot(summary.reg$rsq, xlab = "Number of Variables", ylab = "RSq", type = "b")

plot(summary.reg$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "b")
best_adj_r2 = which.max(summary.reg$adjr2)
points(best_adj_r2, summary.reg$adjr2[best_adj_r2],
       col = "red",cex = 2, pch = 20)

plot(summary.reg$cp, xlab = "Number of Variables", ylab = "Cp", type = 'b')
best_cp = which.min(summary.reg$cp[-c(length(summary.reg$cp))])
points(best_cp, summary.reg$cp[best_cp],
       col = "red", cex = 2, pch = 20)

plot(summary.reg$bic, xlab = "Number of Variables", ylab = "BIC", type = 'b')
best_bic = which.min(summary.reg$bic)
points(best_bic, summary.reg$bic[best_bic],
       col = "red", cex = 2, pch = 20)

```


```{r}
#AV plots for model with 5 potential predictors
library(alr4)
full.5<-lm(G3 ~ G2+G1+famrel+health+absences,data=d2)
avPlots(full.5, id=FALSE)
summary(full.5)
```

```{r}
#test for outliers
par(mfrow = c(1, 2))
plot(full.5, which = 1)
plot(full.5, which = 2)
outlierTest(full.5) #we found several outliers 44,46,62,101,217 in the dataset by looking at the diagnostic plots
influenceIndexPlot(full.5, vars = c('hat', 'Cook'), id=TRUE)
```

```{r}
#check if we need to do transformation
boxCox(full.5)
#no need for transformation
```

```{r}
#new clean data set d3
d3 <- d2[-c(44,46, 62,101,217), ]
full.5.1 <- lm(G3 ~ G2 + G1 + famrel + health + absences, data=d3)
summary(full.5.1)
par(mfrow = c(1, 2))
plot(full.5.1)

#remove 2 predictors: absences and health because of the outliers
full.3<-lm(G3 ~ G2+ G1 + famrel, data=d3)
summary(full.3)
plot(full.3)
anova(full.3)
```

